palette:
  top: '#068e05'
  bottom: '#3fc31d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-77d5b70a/logo.svg'
stylesheets:
  - 'public://color/bartik-77d5b70a/colors.css'
files:
  - 'public://color/bartik-77d5b70a/logo.svg'
  - 'public://color/bartik-77d5b70a/colors.css'
