palette:
  top: '#118e05'
  bottom: '#3ac31d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-fe4610cb/logo.svg'
stylesheets:
  - 'public://color/bartik-fe4610cb/colors.css'
files:
  - 'public://color/bartik-fe4610cb/logo.svg'
  - 'public://color/bartik-fe4610cb/colors.css'
