palette:
  top: '#630213'
  bottom: '#ff1340'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-2761d141/logo.svg'
stylesheets:
  - 'public://color/bartik-2761d141/colors.css'
files:
  - 'public://color/bartik-2761d141/logo.svg'
  - 'public://color/bartik-2761d141/colors.css'
