title: 'Frequently Asked Questions'
description: ''
custom_breadcrumbs: true
display: questions_top
question_listing: ul
qa_mark: 0
question_label: 'Q:'
answer_label: 'A:'
question_length: short
question_long_form: 1
hide_qa_accordion: 0
show_expand_all: 0
use_teaser: 0
back_to_top: 'Back to Top'
disable_node_links: 0
default_sorting: DESC
use_categories: 1
category_display: categories_inline
category_listing: ul
category_hide_qa_accordion: 0
count: 1
answer_category_name: 1
group_questions_top: 1
hide_child_terms: 0
show_term_page_children: 0
omit_vocabulary:
  promotions: promotions
  artwork_type: 0
  color_feature: 0
  faq_category: 0
  illustration_techniques: 0
  locations: 0
  price_list: 0
  private_tags: 0
  product_category: 0
  style_category: 0
  style_tag: 0
  tags: 0
_core:
  default_config_hash: SQxxJIZXuKPvJBBY6_EQCM940iKYgW6QVES9iN4s5h4
