multiple_registration_hidden_customer: 0
multiple_registration_form_mode_register_customer: register
multiple_registration_form_mode_edit_customer: customer_register
multiple_registration_path_creator: creator/register
multiple_registration_url_creator: /user/register/creator
multiple_registration_hidden_creator: 0
multiple_registration_form_mode_register_creator: creator_register
multiple_registration_form_mode_edit_creator: creator_register
