palette:
  top: '#8e4f05'
  bottom: '#c3b71d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-99a71a0f/logo.svg'
stylesheets:
  - 'public://color/bartik-99a71a0f/colors.css'
files:
  - 'public://color/bartik-99a71a0f/logo.svg'
  - 'public://color/bartik-99a71a0f/colors.css'
