palette:
  top: '#8e8905'
  bottom: '#c3ba1d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-2920eda2/logo.svg'
stylesheets:
  - 'public://color/bartik-2920eda2/colors.css'
files:
  - 'public://color/bartik-2920eda2/logo.svg'
  - 'public://color/bartik-2920eda2/colors.css'
