label: 'Formulari del carretó'
display:
  default:
    display_title: Mestre
    display_options:
      exposed_form:
        options:
          submit_button: Aplica
          reset_button_label: Reinicialitza
          exposed_sorts_label: 'Ordena per'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        purchased_entity:
          label: Element
          separator: ', '
        unit_price__number:
          label: Preu
          separator: ', '
        edit_quantity:
          label: Quantitat
        remove_button:
          label: Elimina
        total_price__number:
          label: Total
          separator: ', '
      arguments:
        order_id:
          exception:
            title: Tot
