label: Comentaris
description: 'Cerqueu i gestioneu els comentaris.'
display:
  default:
    display_title: Mestre
    display_options:
      exposed_form:
        options:
          submit_button: Aplica
          reset_button_label: Reinicialitza
          exposed_sorts_label: 'Ordena per'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ anterior'
            next: 'següent ›'
            first: '« primer'
            last: 'últim »'
          expose:
            items_per_page_label: 'Elements per pàgina'
            items_per_page_options_all_label: '- Tot -'
            offset_label: Desplaçament
      fields:
        comment_bulk_form:
          action_title: Acció
        subject:
          label: Assumpte
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Autor
          separator: ', '
        entity_id:
          label: 'Publicat a'
          separator: ', '
        changed:
          label: Actualitzat
          separator: ', '
        operations:
          label: Operacions
        name_1:
          separator: ', '
      filters:
        subject:
          expose:
            label: Assumpte
        combine:
          expose:
            label: 'Nom de l''autor'
        langcode:
          expose:
            label: Llengua
      title: Comentaris
      empty:
        area_text_custom:
          content: 'No hi ha comentaris disponibles.'
      use_more_text: més
  page_published:
    display_title: 'Comentaris publicats'
    display_options:
      menu:
        title: Comentaris
        description: 'Comentaris publicats'
      display_description: 'El llistat de comentaris aprovats.'
  page_unapproved:
    display_title: 'Comentaris sense aprovar'
    display_options:
      menu:
        title: 'Comentaris sense aprovar'
        description: 'Comentaris pendents d''aprovació'
      display_description: 'El llistat de comentaris pendents d''aprovació.'
      filters:
        subject:
          expose:
            label: Assumpte
        combine:
          expose:
            label: 'Nom de l''autor'
        langcode:
          expose:
            label: Llengua
      fields:
        comment_bulk_form:
          action_title: Acció
        subject:
          label: Assumpte
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Autor
          separator: ', '
        entity_id:
          label: 'Publicat a'
          separator: ', '
        changed:
          label: Actualitzat
          separator: ', '
        operations:
          label: Operacions
        name_1:
          separator: ', '
