label: Multimèdia
display:
  default:
    display_title: Mestre
    display_options:
      exposed_form:
        options:
          submit_button: Filtra
          reset_button_label: Reinicialitza
          exposed_sorts_label: 'Ordena per'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elements per pàgina'
            items_per_page_options_all_label: '- Tot -'
            offset_label: Desplaçament
          tags:
            previous: '‹ Anterior'
            next: 'Següent ›'
            first: '« Primer'
            last: 'Darrer »'
      fields:
        media_bulk_form:
          action_title: Acció
        thumbnail__target_id:
          label: Miniatura
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: Tipus
          separator: ', '
        uid:
          label: Autor
          separator: ', '
        status:
          label: Estat
          settings:
            format_custom_true: Publicat
            format_custom_false: 'No publicat'
          separator: ', '
        changed:
          label: Actualitzat
          separator: ', '
        operations:
          label: Operacions
      filters:
        bundle:
          expose:
            label: Tipus
        status:
          expose:
            label: Cert
          group_info:
            label: 'Estat de publicació'
            group_items:
              1:
                title: Publicat
              2:
                title: 'No publicat'
        langcode:
          expose:
            label: Llengua
      title: Multimèdia
      empty:
        area_text_custom:
          content: 'No hi ha mèdia disponible.'
  media_page_list:
    display_title: Multimèdia
    display_options:
      menu:
        title: Multimèdia
