label: 'Bloc de qui està en línia'
description: 'Mostra els noms d''usuari dels usuaris actius més recentment i el nombre total d''usuaris actius.'
display:
  default:
    display_title: Mestre
    display_options:
      exposed_form:
        options:
          submit_button: Aplica
          reset_button_label: Reinicialitza
          exposed_sorts_label: 'Ordena per'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        access:
          expose:
            label: 'Darrer accés'
            description: 'Un usuari es considera connectat per aquest temps d''ençà que va veure per darrer cop una pàgina.'
      title: 'Qui està connectat'
      header:
        result:
          content: 'Actualment hi ha @total usuaris en línia.'
      empty:
        area_text_custom:
          content: 'Actualment no hi ha cap usuari connectat.'
  who_s_online_block:
    display_title: 'Qui està connectat'
    display_options:
      block_description: 'Qui està connectat'
      display_description: 'Una llista d''usuaris que tenen actualment una sessió oberta.'
