label: 'Biblioteca de blocs personalitzats'
description: 'Cerqueu i gestioneu els blocs personalitzats.'
display:
  default:
    display_title: Mestre
    display_options:
      exposed_form:
        options:
          submit_button: Aplica
          reset_button_label: Reinicialitza
          exposed_sorts_label: 'Ordena per'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Següent ›'
          expose:
            items_per_page_label: 'Elements per pàgina'
            items_per_page_options_all_label: '- Tot -'
            offset_label: Desplaçament
      fields:
        info:
          label: 'Descripció del bloc'
          separator: ', '
        type:
          label: 'Tipus de bloc'
          separator: ', '
        changed:
          label: Actualitzat
        operations:
          label: Operacions
      filters:
        info:
          expose:
            label: 'Descripció del bloc'
        type:
          expose:
            label: 'Tipus de bloc'
      title: 'Biblioteca de blocs personalitzats'
      empty:
        area_text_custom:
          content: 'No hi ha blocs personalitzats disponibles.'
  page_1:
    display_title: Pàgina
    display_options:
      menu:
        title: 'Biblioteca de blocs personalitzats'
