label: Vigilant
description: 'Missatges recents del registre'
display:
  default:
    display_title: Mestre
    display_options:
      exposed_form:
        options:
          submit_button: Filtra
          reset_button_label: Reinicialitza
          exposed_sorts_label: 'Ordena per'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elements per pàgina'
            items_per_page_options_all_label: '- Tot -'
            offset_label: Desplaçament
          tags:
            previous: ‹‹
            next: ››
      fields:
        nothing:
          admin_label: Icona
        wid:
          label: WID
        severity:
          label: Severitat
        type:
          label: Tipus
        timestamp:
          label: Data
        message:
          label: Missatge
          alter:
            alt: '{{ message }}'
        name:
          label: Usuari
          separator: ', '
        link:
          label: Operacions
      filters:
        type:
          expose:
            label: Tipus
        severity:
          expose:
            label: Severitat
      title: 'Missatges recents del registre'
      empty:
        area:
          admin_label: 'No hi ha missatges de registre disponibles.'
          content: 'No hi ha missatges de registre disponibles.'
  page:
    display_title: Pàgina
