display:
  default:
    display_title: Mestre
    display_options:
      exposed_form:
        options:
          submit_button: Filtra
          reset_button_label: Reinicialitza
          exposed_sorts_label: 'Ordena per'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elements per pàgina'
            items_per_page_options_all_label: '- Tot -'
            offset_label: Desplaçament
          tags:
            previous: '‹ anterior'
            next: 'següent ›'
            first: '« primer'
            last: 'últim »'
      fields:
        commerce_order_bulk_form:
          action_title: 'Amb la selecció'
        type:
          label: Tipus
          separator: ', '
        store_id:
          label: Botiga
          separator: ', '
        uid:
          label: Client
          separator: ', '
        mail:
          label: 'Correu electrònic'
          separator: ', '
        total_price__number:
          label: Total
          separator: ', '
        changed:
          label: Actualitzat
          separator: ', '
        operations:
          label: Operacions
      filters:
        type:
          expose:
            label: Tipus
  page_1:
    display_title: Pàgina
