settings:
  confirmation_title: Gràcies
handlers:
  email_notification:
    label: 'Notificació per correu electrònic'
    settings:
      from_name: '[webform_submission:values:name:raw]'
      subject: '[webform_submission:values:subject:raw]'
      body: '[webform_submission:values:message:value]'
