settings:
  confirmation_message: 'Gràcies per sol·licitar-ho.'
handlers:
  email_notification:
    label: 'Notificació per correu electrònic'
    settings:
      from_name: '[webform_submission:values:first_name] [webform_submission:values:last_name]'
