palette:
  top: '#84058e'
  bottom: '#1d84c3'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-cf5b2577/logo.svg'
stylesheets:
  - 'public://color/bartik-cf5b2577/colors.css'
files:
  - 'public://color/bartik-cf5b2577/logo.svg'
  - 'public://color/bartik-cf5b2577/colors.css'
