coming_soon_heading: 'Illustrationline.com is cooming!'
coming_soon_body:
  value: "<p>Custom artworks.</p>\r\n"
  format: basic_html
coming_soon_notification: 1
coming_soon_logo: 0
coming_soon_end_date: ''
coming_soon_bg: {  }
coming_soon_copyrights: ''
coming_soon_facebook: ''
coming_soon_twitter: ''
coming_soon_googleplus: ''
coming_soon_linkedin: ''
